name: Init repo for a cargo crate workflow
description: 'Initialize the workflow for a cargo crate (i.e checkout repo, cache cargo, install rust)'
inputs:
  profile:
    description: 'Profile to use (minimal / default)'
    required: true
    default: 'minimal'
  toolchain:
    description: 'Toolchain to install (stable / beta / nightly / <specific version>)'
    required: true
    default: 'stable'
  components:
    description: '(Optional) Toolchain components to install (e.g rustfmt, clippy)'
    required: false
  override:
    description: '(Optionally) Whether or not to override the default toolchain'
    required: false
  cache-key-prefix:
    description: '(Optional) Prefix for caching key'
    required: false
    default: '${{ runner.os }}-'

runs:
  using: 'composite'
  steps:
#    - name: Checkout code
#      uses: actions/checkout@v2

    - name: Cache Cargo Directories
      uses: ./.github/actions/cache_cargo
      with:
        cache-key-prefix: ${{ inputs.key-prefix }}

    - name: Install Rust
      uses: ./.github/actions/install_rust
      with:
        profile: ${{ inputs.profile }}
        toolchain: ${{ inputs.toolchain }}
        override: ${{ inputs.override }}
        components: ${{ inputs.components }}
