[package]
name = "include_proc_macro"
authors = ["orgrinrt", "Hiisi Digital"]
version = "1.0.0"
edition = "2021"

[dependencies]



[clippy]
# Enable all lints that are on by default
default-features = true
# Enable additional lints
# (replace `+` with `-` to disable specific lints)
extra-plugins = [
    "clippy::pedantic",
    "clippy::cargo",
    "+clippy::nursery",
    "+clippy::style",
    "+clippy::complexity",
    "+clippy::perf",
    "+clippy::correctness",
    "+clippy::suspicious",
    "+clippy::deprecated"
]
