//! Every cell of the implementation-path grammar, against every way of declaring a macro.
//!
//! Nine path forms times ten declaration shapes. The set is generated rather than
//! chosen, so a form that works for one kind and not another cannot slip through by
//! being left out of the sample: it is a failing build here.
//!
//! Generated by `generate.py` in this directory. Regenerate rather than hand-editing.

mod scope;
#[allow(unused_imports)]
use scope::*;

mod a_croot;
mod a_sroot;
mod a_umod2;
mod a_unest;
mod d_croot;
mod d_sroot;
mod d_umod2;
mod d_unest;
mod da_croot;
mod da_sroot;
mod da_umod2;
mod da_unest;
mod f_croot;
mod f_sroot;
mod f_umod2;
mod f_unest;
mod ia_croot;
mod ia_sroot;
mod ia_umod2;
mod ia_unest;
mod if_croot;
mod if_sroot;
mod if_umod2;
mod if_unest;
mod la_croot;
mod la_sroot;
mod la_umod2;
mod la_unest;
mod ld_croot;
mod ld_sroot;
mod ld_umod2;
mod ld_unest;
mod lda_croot;
mod lda_sroot;
mod lda_umod2;
mod lda_unest;
mod lf_croot;
mod lf_sroot;
mod lf_umod2;
mod lf_unest;

include_proc_macro::proc_macro!(f_bare -> f_bare_fn);
include_proc_macro::proc_macro!(f_use -> use f_use_fn);
include_proc_macro::proc_macro!(f_mod2 -> f_mod2::imp);
include_proc_macro::proc_macro!(f_emod2 -> mod f_emod2::imp);
include_proc_macro::proc_macro!(f_umod2 -> use f_umod2::imp);
include_proc_macro::proc_macro!(f_nest -> f_nest::b::c::imp);
include_proc_macro::proc_macro!(f_unest -> use f_unest::b::c::imp);
include_proc_macro::proc_macro!(f_lit -> "impls/f_lit.rs"::imp);
include_proc_macro::proc_macro!(f_crel -> @"src/impls/f_crel.rs"::imp);
include_proc_macro::proc_macro!(f_croot -> crate::f_croot::imp);
include_proc_macro::proc_macro!(f_sroot -> self::f_sroot::imp);
include_proc_macro::attr_macro!(a_bare -> a_bare_fn);
include_proc_macro::attr_macro!(a_use -> use a_use_fn);
include_proc_macro::attr_macro!(a_mod2 -> a_mod2::imp);
include_proc_macro::attr_macro!(a_emod2 -> mod a_emod2::imp);
include_proc_macro::attr_macro!(a_umod2 -> use a_umod2::imp);
include_proc_macro::attr_macro!(a_nest -> a_nest::b::c::imp);
include_proc_macro::attr_macro!(a_unest -> use a_unest::b::c::imp);
include_proc_macro::attr_macro!(a_lit -> "impls/a_lit.rs"::imp);
include_proc_macro::attr_macro!(a_crel -> @"src/impls/a_crel.rs"::imp);
include_proc_macro::attr_macro!(a_croot -> crate::a_croot::imp);
include_proc_macro::attr_macro!(a_sroot -> self::a_sroot::imp);
include_proc_macro::derive_macro!((DDBare) -> d_bare_fn);
include_proc_macro::derive_macro!((DDUse) -> use d_use_fn);
include_proc_macro::derive_macro!((DDMod2) -> d_mod2::imp);
include_proc_macro::derive_macro!((DDEmod2) -> mod d_emod2::imp);
include_proc_macro::derive_macro!((DDUmod2) -> use d_umod2::imp);
include_proc_macro::derive_macro!((DDNest) -> d_nest::b::c::imp);
include_proc_macro::derive_macro!((DDUnest) -> use d_unest::b::c::imp);
include_proc_macro::derive_macro!((DDLit) -> "impls/d_lit.rs"::imp);
include_proc_macro::derive_macro!((DDCrel) -> @"src/impls/d_crel.rs"::imp);
include_proc_macro::derive_macro!((DDCroot) -> crate::d_croot::imp);
include_proc_macro::derive_macro!((DDSroot) -> self::d_sroot::imp);
include_proc_macro::derive_macro!((DDaBare, attributes(alpha, beta)) -> da_bare_fn);
include_proc_macro::derive_macro!((DDaUse, attributes(alpha, beta)) -> use da_use_fn);
include_proc_macro::derive_macro!((DDaMod2, attributes(alpha, beta)) -> da_mod2::imp);
include_proc_macro::derive_macro!((DDaEmod2, attributes(alpha, beta)) -> mod da_emod2::imp);
include_proc_macro::derive_macro!((DDaUmod2, attributes(alpha, beta)) -> use da_umod2::imp);
include_proc_macro::derive_macro!((DDaNest, attributes(alpha, beta)) -> da_nest::b::c::imp);
include_proc_macro::derive_macro!((DDaUnest, attributes(alpha, beta)) -> use da_unest::b::c::imp);
include_proc_macro::derive_macro!((DDaLit, attributes(alpha, beta)) -> "impls/da_lit.rs"::imp);
include_proc_macro::derive_macro!((DDaCrel, attributes(alpha, beta)) -> @"src/impls/da_crel.rs"::imp);
include_proc_macro::derive_macro!((DDaCroot, attributes(alpha, beta)) -> crate::da_croot::imp);
include_proc_macro::derive_macro!((DDaSroot, attributes(alpha, beta)) -> self::da_sroot::imp);
include_proc_macro::macros!(function(lf_bare) -> lf_bare_fn);
include_proc_macro::macros!(function(lf_use) -> use lf_use_fn);
include_proc_macro::macros!(function(lf_mod2) -> lf_mod2::imp);
include_proc_macro::macros!(function(lf_emod2) -> mod lf_emod2::imp);
include_proc_macro::macros!(function(lf_umod2) -> use lf_umod2::imp);
include_proc_macro::macros!(function(lf_nest) -> lf_nest::b::c::imp);
include_proc_macro::macros!(function(lf_unest) -> use lf_unest::b::c::imp);
include_proc_macro::macros!(function(lf_lit) -> "impls/lf_lit.rs"::imp);
include_proc_macro::macros!(function(lf_crel) -> @"src/impls/lf_crel.rs"::imp);
include_proc_macro::macros!(function(lf_croot) -> crate::lf_croot::imp);
include_proc_macro::macros!(function(lf_sroot) -> self::lf_sroot::imp);
include_proc_macro::macros!(attribute(la_bare) -> la_bare_fn);
include_proc_macro::macros!(attribute(la_use) -> use la_use_fn);
include_proc_macro::macros!(attribute(la_mod2) -> la_mod2::imp);
include_proc_macro::macros!(attribute(la_emod2) -> mod la_emod2::imp);
include_proc_macro::macros!(attribute(la_umod2) -> use la_umod2::imp);
include_proc_macro::macros!(attribute(la_nest) -> la_nest::b::c::imp);
include_proc_macro::macros!(attribute(la_unest) -> use la_unest::b::c::imp);
include_proc_macro::macros!(attribute(la_lit) -> "impls/la_lit.rs"::imp);
include_proc_macro::macros!(attribute(la_crel) -> @"src/impls/la_crel.rs"::imp);
include_proc_macro::macros!(attribute(la_croot) -> crate::la_croot::imp);
include_proc_macro::macros!(attribute(la_sroot) -> self::la_sroot::imp);
include_proc_macro::macros!(derive(DLdBare) -> ld_bare_fn);
include_proc_macro::macros!(derive(DLdUse) -> use ld_use_fn);
include_proc_macro::macros!(derive(DLdMod2) -> ld_mod2::imp);
include_proc_macro::macros!(derive(DLdEmod2) -> mod ld_emod2::imp);
include_proc_macro::macros!(derive(DLdUmod2) -> use ld_umod2::imp);
include_proc_macro::macros!(derive(DLdNest) -> ld_nest::b::c::imp);
include_proc_macro::macros!(derive(DLdUnest) -> use ld_unest::b::c::imp);
include_proc_macro::macros!(derive(DLdLit) -> "impls/ld_lit.rs"::imp);
include_proc_macro::macros!(derive(DLdCrel) -> @"src/impls/ld_crel.rs"::imp);
include_proc_macro::macros!(derive(DLdCroot) -> crate::ld_croot::imp);
include_proc_macro::macros!(derive(DLdSroot) -> self::ld_sroot::imp);
include_proc_macro::macros!(derive(DLdaBare, attributes(alpha, beta)) -> lda_bare_fn);
include_proc_macro::macros!(derive(DLdaUse, attributes(alpha, beta)) -> use lda_use_fn);
include_proc_macro::macros!(derive(DLdaMod2, attributes(alpha, beta)) -> lda_mod2::imp);
include_proc_macro::macros!(derive(DLdaEmod2, attributes(alpha, beta)) -> mod lda_emod2::imp);
include_proc_macro::macros!(derive(DLdaUmod2, attributes(alpha, beta)) -> use lda_umod2::imp);
include_proc_macro::macros!(derive(DLdaNest, attributes(alpha, beta)) -> lda_nest::b::c::imp);
include_proc_macro::macros!(derive(DLdaUnest, attributes(alpha, beta)) -> use lda_unest::b::c::imp);
include_proc_macro::macros!(derive(DLdaLit, attributes(alpha, beta)) -> "impls/lda_lit.rs"::imp);
include_proc_macro::macros!(derive(DLdaCrel, attributes(alpha, beta)) -> @"src/impls/lda_crel.rs"::imp);
include_proc_macro::macros!(derive(DLdaCroot, attributes(alpha, beta)) -> crate::lda_croot::imp);
include_proc_macro::macros!(derive(DLdaSroot, attributes(alpha, beta)) -> self::lda_sroot::imp);
include_proc_macro::macros!(function -> if_mod2::if_mod2);
include_proc_macro::macros!(function -> mod if_emod2::if_emod2);
include_proc_macro::macros!(function -> use if_umod2::if_umod2);
include_proc_macro::macros!(function -> if_nest::b::c::if_nest);
include_proc_macro::macros!(function -> use if_unest::b::c::if_unest);
include_proc_macro::macros!(function -> "impls/if_lit.rs"::if_lit);
include_proc_macro::macros!(function -> @"src/impls/if_crel.rs"::if_crel);
include_proc_macro::macros!(function -> crate::if_croot::if_croot);
include_proc_macro::macros!(function -> self::if_sroot::if_sroot);
include_proc_macro::macros!(attribute -> ia_mod2::ia_mod2);
include_proc_macro::macros!(attribute -> mod ia_emod2::ia_emod2);
include_proc_macro::macros!(attribute -> use ia_umod2::ia_umod2);
include_proc_macro::macros!(attribute -> ia_nest::b::c::ia_nest);
include_proc_macro::macros!(attribute -> use ia_unest::b::c::ia_unest);
include_proc_macro::macros!(attribute -> "impls/ia_lit.rs"::ia_lit);
include_proc_macro::macros!(attribute -> @"src/impls/ia_crel.rs"::ia_crel);
include_proc_macro::macros!(attribute -> crate::ia_croot::ia_croot);
include_proc_macro::macros!(attribute -> self::ia_sroot::ia_sroot);

mod bulk;

// Asserted by compiling: see bulk.rs.
include_proc_macro::macros!(
    function(bulk0) -> use bulk::i0,
    function(bulk1) -> use bulk::i1,
    function(bulk2) -> use bulk::i2,
    function(bulk3) -> use bulk::i3,
    function(bulk4) -> use bulk::i4,
    function(bulk5) -> use bulk::i5,
    function(bulk6) -> use bulk::i6,
    function(bulk7) -> use bulk::i7,
    function(bulk8) -> use bulk::i8,
    function(bulk9) -> use bulk::i9,
    function(bulk10) -> use bulk::i10,
    function(bulk11) -> use bulk::i11,
    function(bulk12) -> use bulk::i12,
    function(bulk13) -> use bulk::i13,
    function(bulk14) -> use bulk::i14,
    function(bulk15) -> use bulk::i15,
    function(bulk16) -> use bulk::i16,
    function(bulk17) -> use bulk::i17,
    function(bulk18) -> use bulk::i18,
    function(bulk19) -> use bulk::i19,
    function(bulk20) -> use bulk::i20,
    function(bulk21) -> use bulk::i21,
    function(bulk22) -> use bulk::i22,
    function(bulk23) -> use bulk::i23,
    function(bulk24) -> use bulk::i24,
    function(bulk25) -> use bulk::i25,
    function(bulk26) -> use bulk::i26,
    function(bulk27) -> use bulk::i27,
    function(bulk28) -> use bulk::i28,
    function(bulk29) -> use bulk::i29,
    function(bulk30) -> use bulk::i30,
    function(bulk31) -> use bulk::i31,
    function(bulk32) -> use bulk::i32,
    function(bulk33) -> use bulk::i33,
    function(bulk34) -> use bulk::i34,
    function(bulk35) -> use bulk::i35,
    function(bulk36) -> use bulk::i36,
    function(bulk37) -> use bulk::i37,
    function(bulk38) -> use bulk::i38,
    function(bulk39) -> use bulk::i39,
    function(bulk40) -> use bulk::i40,
    function(bulk41) -> use bulk::i41,
    function(bulk42) -> use bulk::i42,
    function(bulk43) -> use bulk::i43,
    function(bulk44) -> use bulk::i44,
    function(bulk45) -> use bulk::i45,
    function(bulk46) -> use bulk::i46,
    function(bulk47) -> use bulk::i47,
    function(bulk48) -> use bulk::i48,
    function(bulk49) -> use bulk::i49,
    function(bulk50) -> use bulk::i50,
    function(bulk51) -> use bulk::i51,
    function(bulk52) -> use bulk::i52,
    function(bulk53) -> use bulk::i53,
    function(bulk54) -> use bulk::i54,
    function(bulk55) -> use bulk::i55,
    function(bulk56) -> use bulk::i56,
    function(bulk57) -> use bulk::i57,
    function(bulk58) -> use bulk::i58,
    function(bulk59) -> use bulk::i59,
    function(bulk60) -> use bulk::i60,
    function(bulk61) -> use bulk::i61,
    function(bulk62) -> use bulk::i62,
    function(bulk63) -> use bulk::i63,
    function(bulk64) -> use bulk::i64,
    function(bulk65) -> use bulk::i65,
    function(bulk66) -> use bulk::i66,
    function(bulk67) -> use bulk::i67,
    function(bulk68) -> use bulk::i68,
    function(bulk69) -> use bulk::i69,
    function(bulk70) -> use bulk::i70,
    function(bulk71) -> use bulk::i71,
    function(bulk72) -> use bulk::i72,
    function(bulk73) -> use bulk::i73,
    function(bulk74) -> use bulk::i74,
    function(bulk75) -> use bulk::i75,
    function(bulk76) -> use bulk::i76,
    function(bulk77) -> use bulk::i77,
    function(bulk78) -> use bulk::i78,
    function(bulk79) -> use bulk::i79,
    function(bulk80) -> use bulk::i80,
    function(bulk81) -> use bulk::i81,
    function(bulk82) -> use bulk::i82,
    function(bulk83) -> use bulk::i83,
    function(bulk84) -> use bulk::i84,
    function(bulk85) -> use bulk::i85,
    function(bulk86) -> use bulk::i86,
    function(bulk87) -> use bulk::i87,
    function(bulk88) -> use bulk::i88,
    function(bulk89) -> use bulk::i89,
    function(bulk90) -> use bulk::i90,
    function(bulk91) -> use bulk::i91,
    function(bulk92) -> use bulk::i92,
    function(bulk93) -> use bulk::i93,
    function(bulk94) -> use bulk::i94,
    function(bulk95) -> use bulk::i95,
    function(bulk96) -> use bulk::i96,
    function(bulk97) -> use bulk::i97,
    function(bulk98) -> use bulk::i98,
    function(bulk99) -> use bulk::i99,
);
