name: Install Rust
description: 'Install the Rust toolchain'
inputs:
  profile:
    description: 'Profile to use (minimal / default)'
    required: true
    default: 'minimal'
  toolchain:
    description: 'Toolchain to install (stable / beta / nightly / <specific version>)'
    required: true
    default: 'stable'
  components:
    description: 'Components to install with the toolchain'
    required: false
  override:
    description: 'Whether or not to override the default toolchain'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: ${{ inputs.profile }}
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        override: ${{ inputs.override }}
