name: Crate audit

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  cargo_audit_and_deny:
    runs-on: ubuntu-latest
    if: contains(toJSON(github.event.commits[*].modified), '**/Cargo.toml')
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
        
      - name: Init crate workflow
        uses: ./.github/actions/init_crate_workflow
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Cargo Deny Check
        run: cargo deny check

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Cargo Audit
        run: cargo audit
