name: crate cicd - push to main

on:
  push:
    branches:
      - main
    inputs:
      ref:
        description: 'Which tag/branch to use of the external crate_ci workflow'
        default: "1.0.1"
        type: string
    secrets:
      CRATES_IO_TOKEN:
        required: false
      GH_RELEASE_TOKEN:
        required: false

jobs:
  call_crate_cicd:
    uses: orgrinrt/cicd/.github/workflows/crate_ci.yml@${{ inputs.ref }}
    secrets:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
    with:
      ref: ${{ inputs.ref }}
      profile: 'minimal'
      toolchain: 'stable'
      override: true
      deploy: false
      force_build: true
      force_tests: true
