name:  'Crate: Release'

on:
  push:
    # triggers the workflow when a tag matching the defined pattern is pushed
    tags:
      - 'v*.*.*'
      - '*.*.*'
      - 'release-*.*.*'
    secrets:
      CRATES_IO_TOKEN:
        required: true
      GH_RELEASE_TOKEN:
        required: true

jobs:
  audit:
    uses: orgrinrt/cicd/.github/workflows/crate_audit.yml@main
  
  call_crate_cicd:
    uses: orgrinrt/cicd/.github/workflows/crate_ci.yml@main
    secrets:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
    with:
      profile: 'minimal'
      toolchain: 'stable'
      override: true
      deploy_cratesio: true
      force_build: true
      force_tests: true
      force_deploy: false
      auto_bump: true
